// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/greeting.proto

package greeting

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Created              string   `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e54e98d9a01155c, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Greeting) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Greeting) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Greeting) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

type GreetingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingRequest) Reset()         { *m = GreetingRequest{} }
func (m *GreetingRequest) String() string { return proto.CompactTextString(m) }
func (*GreetingRequest) ProtoMessage()    {}
func (*GreetingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e54e98d9a01155c, []int{1}
}

func (m *GreetingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingRequest.Unmarshal(m, b)
}
func (m *GreetingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingRequest.Marshal(b, m, deterministic)
}
func (m *GreetingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingRequest.Merge(m, src)
}
func (m *GreetingRequest) XXX_Size() int {
	return xxx_messageInfo_GreetingRequest.Size(m)
}
func (m *GreetingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingRequest proto.InternalMessageInfo

type GreetingResponse struct {
	Greeting             []*Greeting `protobuf:"bytes,1,rep,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GreetingResponse) Reset()         { *m = GreetingResponse{} }
func (m *GreetingResponse) String() string { return proto.CompactTextString(m) }
func (*GreetingResponse) ProtoMessage()    {}
func (*GreetingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e54e98d9a01155c, []int{2}
}

func (m *GreetingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingResponse.Unmarshal(m, b)
}
func (m *GreetingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingResponse.Marshal(b, m, deterministic)
}
func (m *GreetingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingResponse.Merge(m, src)
}
func (m *GreetingResponse) XXX_Size() int {
	return xxx_messageInfo_GreetingResponse.Size(m)
}
func (m *GreetingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingResponse proto.InternalMessageInfo

func (m *GreetingResponse) GetGreeting() []*Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greeting.Greeting")
	proto.RegisterType((*GreetingRequest)(nil), "greeting.GreetingRequest")
	proto.RegisterType((*GreetingResponse)(nil), "greeting.GreetingResponse")
}

func init() { proto.RegisterFile("proto/greeting.proto", fileDescriptor_6e54e98d9a01155c) }

var fileDescriptor_6e54e98d9a01155c = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0xc6, 0x20,
	0x14, 0x85, 0x53, 0x7e, 0xa3, 0x15, 0x13, 0xad, 0xc4, 0x01, 0x1b, 0x87, 0x86, 0xa9, 0x53, 0x1b,
	0xeb, 0x1b, 0xb8, 0xb8, 0xd7, 0xd1, 0x09, 0xdb, 0x1b, 0x24, 0x51, 0xa8, 0x80, 0x7d, 0x00, 0x5f,
	0xc1, 0x47, 0xf3, 0x15, 0x7c, 0x10, 0x53, 0xa0, 0xf4, 0x1f, 0x3a, 0x9e, 0xfb, 0x1d, 0xb8, 0xe7,
	0x1e, 0x7c, 0x33, 0x19, 0xed, 0x74, 0x2b, 0x0c, 0x80, 0x93, 0x4a, 0x34, 0x5e, 0x92, 0x7c, 0xd5,
	0xe5, 0x9d, 0xd0, 0x5a, 0xbc, 0x43, 0xcb, 0x27, 0xd9, 0x72, 0xa5, 0xb4, 0xe3, 0x4e, 0x6a, 0x65,
	0x83, 0x8f, 0xbd, 0xe1, 0xfc, 0x29, 0x3a, 0xc9, 0x25, 0x46, 0x72, 0xa4, 0x59, 0x95, 0xd5, 0xe7,
	0x3d, 0x92, 0x23, 0xa1, 0xf8, 0xcc, 0x82, 0x99, 0xe5, 0x00, 0x14, 0xf9, 0xe1, 0x2a, 0x17, 0xf2,
	0x01, 0xd6, 0x72, 0x01, 0xf4, 0x10, 0x48, 0x94, 0x0b, 0x19, 0x0c, 0x70, 0x07, 0x23, 0x3d, 0x09,
	0x24, 0x4a, 0x76, 0x8d, 0xaf, 0xd6, 0x4d, 0x3d, 0x7c, 0x7e, 0x81, 0x75, 0xec, 0x11, 0x17, 0xdb,
	0xc8, 0x4e, 0x5a, 0x59, 0x20, 0x0d, 0x4e, 0xd1, 0x69, 0x56, 0x1d, 0xea, 0x8b, 0x8e, 0x34, 0xe9,
	0xb6, 0xe4, 0x4e, 0x9e, 0x4e, 0x6d, 0xdf, 0x3e, 0xc7, 0x74, 0x2f, 0x47, 0x37, 0xdd, 0xee, 0x3c,
	0x0e, 0xdb, 0xcb, 0x72, 0x0f, 0x85, 0x14, 0x8c, 0x7e, 0xff, 0xfe, 0xfd, 0x20, 0x42, 0x0a, 0x5f,
	0xdb, 0x7c, 0x9f, 0xea, 0x7d, 0x3d, 0xf5, 0xbd, 0x3d, 0xfc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x97,
	0x94, 0x3c, 0xfc, 0x77, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreetingServiceClient is the client API for GreetingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetingServiceClient interface {
	Greeting(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error)
}

type greetingServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetingServiceClient(cc *grpc.ClientConn) GreetingServiceClient {
	return &greetingServiceClient{cc}
}

func (c *greetingServiceClient) Greeting(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error) {
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, "/greeting.GreetingService/Greeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetingServiceServer is the server API for GreetingService service.
type GreetingServiceServer interface {
	Greeting(context.Context, *GreetingRequest) (*GreetingResponse, error)
}

// UnimplementedGreetingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetingServiceServer struct {
}

func (*UnimplementedGreetingServiceServer) Greeting(ctx context.Context, req *GreetingRequest) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greeting not implemented")
}

func RegisterGreetingServiceServer(s *grpc.Server, srv GreetingServiceServer) {
	s.RegisterService(&_GreetingService_serviceDesc, srv)
}

func _GreetingService_Greeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingServiceServer).Greeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greeting.GreetingService/Greeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingServiceServer).Greeting(ctx, req.(*GreetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreetingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greeting.GreetingService",
	HandlerType: (*GreetingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greeting",
			Handler:    _GreetingService_Greeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/greeting.proto",
}
